name: Deploy
on:
  pull_request:
    types: [closed]
    branches: [main]

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  deploy:
    # This ensures it ONLY runs if the PR was actually merged, not just closed
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      AWS_REGION: 'us-east-2'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies & Test
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pytest
          pytest -q || [ $? -eq 5 ] # Run tests, ignore "no tests found" error

      - name: Set up AWS SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Build and Deploy
        run: |
          sam build --use-container
          sam deploy \
            --stack-name picklebit-backend \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --capabilities CAPABILITY_IAM \
            --region ${{ env.AWS_REGION }} \
            --resolve-s3